"""Add favorites and helpful features

Revision ID: 48e8bddd610e
Revises: 1c1819265ad8
Create Date: 2026-02-10 22:04:46.372007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e8bddd610e'
down_revision: Union[str, Sequence[str], None] = '1c1819265ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_helpful',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('helpful_count', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('context_tags', sa.String(), nullable=True))
    op.alter_column('article_likes', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('article_likes', 'article_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('article_likes_user_id_article_id_key'), 'article_likes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('article_likes_user_id_article_id_key'), 'article_likes', ['user_id', 'article_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('article_likes', 'article_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('article_likes', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('answers', 'context_tags')
    op.drop_column('answers', 'helpful_count')
    op.drop_table('answer_helpful')
    op.drop_table('user_saved_content')
    # ### end Alembic commands ###
